# Generated by Django 6.0.3 on 2026-04-23 09:19

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character_class', models.CharField(choices=[('ranger', '🏹 Рейнджер (кардио и ноги)'), ('paladin', '🛡️ Паладин (грудь и жим)'), ('barbarian', '⚔️ Варвар (спина и сила)'), ('mage', '🧙 Маг (кор и мобильность)')], default='paladin', max_length=20, verbose_name='Класс')),
                ('level', models.PositiveSmallIntegerField(default=1, verbose_name='Уровень')),
                ('rank', models.CharField(default='Серебряный крестоносец', max_length=100, verbose_name='Ранг')),
                ('experience', models.PositiveIntegerField(default=0, verbose_name='Опыт')),
                ('favorite_dungeon', models.CharField(blank=True, default='', max_length=100, verbose_name='Любимое подземелье')),
                ('home_location', models.CharField(blank=True, max_length=100, verbose_name='Домашняя локация')),
                ('main_goal', models.CharField(blank=True, max_length=200, verbose_name='Главная цель')),
                ('bio', models.TextField(blank=True, verbose_name='Биография / девиз')),
                ('banner_color', models.CharField(choices=[('gold', 'Королевское золото'), ('crimson', 'Багровая осада'), ('emerald', 'Изумрудная роща'), ('blue', 'Магический синий')], default='gold', max_length=30, verbose_name='Цвет баннера профиля')),
                ('display_name', models.CharField(blank=True, max_length=150, verbose_name='Отображаемое имя')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'gif'])], verbose_name='Аватар')),
                ('achievements', models.JSONField(blank=True, default=dict, verbose_name='Достижения')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Профиль',
                'verbose_name_plural': 'Профили',
            },
        ),
    ]
