# Generated by Django 6.0.3 on 2026-04-27 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profiles', '0002_remove_profile_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='achievements',
        ),
        migrations.AddField(
            model_name='profile',
            name='completed_tasks',
            field=models.PositiveIntegerField(default=0, verbose_name='Выполнено заданий'),
        ),
    ]
