# Generated by Django 6.0.3 on 2026-05-01 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Profiles', '0003_remove_profile_achievements_profile_completed_tasks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='rank',
        ),
    ]
