# Generated by Django 6.0.3 on 2026-05-01 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Profiles', '0004_remove_profile_rank'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='banner_color',
        ),
    ]
