# Generated by Django 6.0.3 on 2026-04-27 11:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tasks', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clantask',
            name='assignee',
        ),
        migrations.AddField(
            model_name='clantask',
            name='participants',
            field=models.ManyToManyField(blank=True, related_name='tasks_participating', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='clantask',
            name='deadline',
            field=models.DateField(blank=True, null=True),
        ),
    ]
