# Generated by Django 6.0.3 on 2026-04-27 11:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tasks', '0002_remove_clantask_assignee_clantask_participants_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clantaskcompletion',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completions', to='Tasks.clantask'),
        ),
    ]
